---
title: "Final Project Group 8"
author:
- affiliation: Department of Industrial and Systems Engineering, Auburn University
  name: 'Amir Mehdizadeh ^[Email: azm0127@auburn.edu </a>]'
- affiliation: Department of Industrial and Systems Engineering, Auburn University
  name: 'Jiafeng Ye ^[Email: jzy0087@auburn.edu </a>]'
- affiliation: Department of Psychological Sciences, Auburn University
  name: 'David Haste ^[Email: dah0048@auburn.edu </a>]'
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: show
    number_sections: no
    paged_df: yes
    theme: simplex
    toc: yes
    toc_float: yes
  includes:
    in_header: structure.tex
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

# add a column with ones to the feature matrix
shapeX = function(X) {
        X = as.matrix(X)
        X = cbind(1, X)
        X
}

shapeY = function(Y) {
        Y = as.matrix(Y)
        Y
}

# least squares estimators that minimizer
L  = function(Y, X, beta){  
        loss = sum(t(Y - X%*%beta)%*%(Y - X%*%beta))
        loss 
}

 # define the standard quadratic loss function
  sqfn<-function(y, x, beta){  
  loss <- sum((x%*%as.vector(beta)- y)^2)
return(loss) 
  }



my_lm = function(response, predictors, alpha) {
  
  # Make sure data formats are appropriate
  response <- shapeY(response)
  predictors <- shapeX(predictors)
  
  
  # Define parameters
  n <- length(response)
  p <- dim(predictors)[2]
  df <- n - p
  
  # Define the initial beta
  beta0 = matrix(0, nrow  = p, ncol = 1)
  beta0[1,1] = mean(response[,1])
  for (i in 2:p) {
        beta0[i,1] = cov(response[,1], predictors[,i]) / var(predictors[,i])
  }
    
#sqfn(response,predictors,beta0)
  fit = optim(par = beta0, fn = L, predictors = predictors, response = response)
  beta.hat = fit$par
  
# Estimate of the residual variance (sigma2) from Eq. (6.3)
  # Compute residuals
  resids <- response - predictors%*%as.vector(beta.hat) 
  sigma2.hat <- (1/df)*(t(resids)%*%resids)
  
  # Estimate of the variance of the estimated beta from Eq. (6.2)
  var.beta <- as.vector(sigma2.hat)*solve(t(predictors)%*%predictors)
  
  # Estimate of the confidence interval based on alpha
  quant <- 1 - alpha/2
  ci.beta <- c(beta.hat - qnorm(p = quant)*sqrt(var.beta), beta.hat + qnorm(p = quant)*sqrt(var.beta))
  
  # Return all estimated values
  return(list(beta = beta.hat, sigma2 = sigma2.hat, 
              variance_beta = var.beta, ci = ci.beta))
}
```

```{r}
my_lm(y,x,0.05)
```

##Graphing Plots
```{r}
#Plotting the reisdual vs. fitted plots
plot(fitted(fit), resids)

#Plotting the q-q plots
qqnorm(resids)

#Plotting Histogram
plot(density(resids))
```

